ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "fastrl"
  site-url: "https://josiahls.github.io/fast-reinforcement-learning-2/"
  description: "Fastrl is a Reinforcement Learning library that extends Fastai. This project is not affiliated with Fastai or Jeremy Howard."
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/josiahls/fast-reinforcement-learning-2/tree/master/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/josiahls/fast-reinforcement-learning-2/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
