# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/20g_qlearning.dddqn.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch.nn.utils as nn_utils
from fastai.torch_basics import *
from fastai.data.all import *
from fastai.basics import *
from dataclasses import field,asdict
from typing import List,Any,Dict,Callable
from collections import deque
import gym
import torch.multiprocessing as mp
from torch.optim import *

from ..data import *
from ..async_data import *
from ..basic_agents import *
from ..learner import *
from ..metrics import *
from ..ptan_extension import *
from .dqn import *
from .dqn_target import *
from .dqn_double import *
from .dqn_dueling import *

if IN_NOTEBOOK:
    from IPython import display
    import PIL.Image