version: "3"
services:
  fastrl: &fastrl
    restart: unless-stopped
    working_dir: /home/fastrl_user/fastrl
    build:
      dockerfile: fastrl.Dockerfile
      context: .
    image: josiahls/fastrl-dev:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    shm_size: 16000000000
    volumes:
      - .:/home/fastrl_user/fastrl/
      - ~/.ssh:/home/fastrl_user/.ssh:rw
    network_mode: host # for GitHub Codespaces https://github.com/features/codespaces/

  dep_watcher:
    <<: *fastrl
    command: watchmedo shell-command --command fastrl_make_requirements --pattern *.ini --recursive --drop

  quarto:
    <<: *fastrl
    restart: unless-stopped
    working_dir: /home/fastrl_user/fastrl/nbs/_docs
    volumes:
      - .:/home/fastrl_user/fastrl/
    command: nbdev_preview
