package:
  name: fastrl
  version: 0.0.30
source:
  sha256: 1b40765204bed1705c78898deea9dda5b57bb896c0c09cf22e82eb2e24dec435
  url: https://files.pythonhosted.org/packages/80/22/de9d68c3b308c3734947e06798c81596616a0e170659c8d121e86b25e43a/fastrl-0.0.30.tar.gz
about:
  dev_url: https://josiahls.github.io
  doc_url: https://josiahls.github.io
  home: https://josiahls.github.io
  license: Apache Software
  license_family: APACHE
  summary: fastrl is a reinforcement learning library that extends Fastai. This project
    is not affiliated with fastai or Jeremy Howard.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - josiahls
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai>=2.0.0
  run:
  - pip
  - python
  - packaging
  - fastai>=2.0.0
test:
  imports:
  - fastrl
