# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02b_fastai.data.load.ipynb (unless otherwise specified).

__all__ = []

# Cell
# Python native modules
import os
# Third party libs
from fastcore.all import *
from fastai.torch_basics import *
from torch.utils.data.dataloader import DataLoader as OrgDataLoader
# Local modules
from ..loop import *

from fastai.data.load import DataLoader as FastaiDataLoader

from torchdata.datapipes.iter import HttpReader