name: fastrl
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python=3.7
  - pip
  - cuda100
  - fastprogress
#  - pytorch>=1.6.0
  - fastai
  - jupyter
  - notebook
  - setuptools
  - pip:
      - pytest
      - nvidia-ml-py3
      - dataclasses
#      - numpy==1.17.4
      - pandas
      - pyyaml
      - opencv-contrib-python
      - requests
      - sklearn
      - cython
      - gym
      - easydict
      - matplotlib
      - jupyter_console
      - moviepy
      - pygifsicle
      - jupyterlab
      - nbdev
      - jupyter
      - jupyterthemes
      - fastcore