repository: josiahls/fast-reinforcement-learning-2
output: web
topnav_title: fastrl
site_title: fastrl
company_name:
github_editme_path: 
use_math: true
google_analytics:
google_search:

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000

exclude:
  - .idea/
  - .gitignore
  - vendor

feedback_disable: true

highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars:
- home_sidebar

description: "Documentation for the deploy2 library"
# theme: jekyll-theme-cayman


baseurl: /fast-reinforcement-learning-2/

