# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/07_Agents/01_Discrete/12n_agents.dqn.dueling.ipynb.

# %% auto 0
__all__ = ['DuelingHead']

# %% ../../../nbs/07_Agents/01_Discrete/12n_agents.dqn.dueling.ipynb 2
# Python native modules
# Third party libs
import torch
from torch import nn
# Local modules
from fastrl.agents.dqn.basic import (
    DQN,
    DQNAgent
)
from .target import DQNTargetLearner

# %% ../../../nbs/07_Agents/01_Discrete/12n_agents.dqn.dueling.ipynb 5
class DuelingHead(nn.Module):
    def __init__(
            self,
            hidden: int, # Input into the DuelingHead, likely a hidden layer input
            n_actions: int, # Number/dim of actions to output
            lin_cls = nn.Linear
        ):
        super().__init__()
        self.val = lin_cls(hidden,1)
        self.adv = lin_cls(hidden,n_actions)

    def forward(self,xi):
        val,adv = self.val(xi),self.adv(xi)
        xi = val.expand_as(adv)+(adv-adv.mean()).squeeze(0)
        return xi
