name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master", "update_to_nbdev_2", "*docs" ]
  workflow_dispatch:

env:
  PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/nightly/cu113

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Install Dependencies
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r extra/requirements.txt
        pip uninstall -y torch 
        # pip install --pre torch torchdata
        pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/nightly/cu113 --upgrade
    - uses: fastai/workflows/quarto-ghp@master
