name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master", "update_to_nbdev_2", "*docs" ]
  workflow_dispatch:

env:
  PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/nightly/cu113

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs:
      using: 'docker'
      image: 'josiahls/fastrl-dev:latest'
    steps: 
    - uses: actions/checkout@v3
    - name: Install Dependencies
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y torch 
        pip install fastai>=2.7.8 --no-dependencies
        pip install -e ".[dev]" --upgrade
    - uses: fastai/workflows/quarto-ghp@master
